export const SKILLS = {
    frontend: [
        { name: 'JavaScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg', level: 5 },
        { name: 'TypeScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg', level: 6 },
        { name: 'React', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg', level: 6 },
        { name: 'Tailwind CSS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg', level: 6 },
    ],
    backend: [
        { name: 'Node.js', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg', level: 7 },
        { name: 'NestJS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nestjs/nestjs-original.svg', level: 7 },
        { name: 'TypeORM', icon: 'https://typeorm.io/img/typeorm-icon-colored.png', level: 6 },
        { name: 'Express.js', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg', level: 5 },
        { name: 'OpenAI API', icon: null, level: 6 },
    ],
    database: [
        { name: 'PostgreSQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg', level: 7 },
        { name: 'MySQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg', level: 5 },
        { name: 'Firebird', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/firebird/firebird-original.svg', level: 7 },
    ],
    tools: [
        { name: 'Git', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg', level: 8 },
        { name: 'Docker', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg', level: 6 },
        { name: 'n8n', icon: 'https://devicons.railway.com/i/n8n.svg', level: 6 },
        { name: 'Easypanel', icon: null, level: 6 },
        { name: 'Grafana', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/grafana/grafana-original.svg', level: 3 },
        { name: 'Jest', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jest/jest-plain.svg', level: 4 },
        { name: 'Agile/Kanban', icon: null, level: 5 },
        { name: 'AWS', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg', level: 4 }
    ],
}

// ─── Translations ─────────────────────────────────────────────────────────────

export const T = {
    pt: {
        openToWork: 'Disponível para oportunidades',
        roles: ['Desenvolvedor Back-End', 'Engenheiro de Software', 'Desenvolvedor Full-Stack'],
        location: 'Brasília, DF – Brasil',
        repos: 'Repositórios',
        followers: 'Seguidores',
        following: 'Seguindo',
        about: 'sobre',
        aboutText: 'Desenvolvedor Full-Stack com foco em back-end, especializado em NestJS, TypeORM e PostgreSQL. Experiência prática no desenvolvimento de APIs REST, automações com n8n e integrações com serviços externos como OpenAI e Evolution API. Trabalho com Docker, versionamento Git e deploy via Easypanel, monitorando ambientes com Grafana em ciclos ágeis com Kanban. Cursando Engenharia de Software, busco constantemente evoluir técnica e profissionalmente.',
        experience: 'experiência',
        projects: 'projetos',
        education: 'educação',
        skills: 'habilidades',
        blog: 'blog',
        present: 'atual',
        website: 'acessar',
        footer: '© {year} · Lucas G. Amorim Steffen',
        promptPrefix: '~/portfolio',
        experience_items: [
            {
                role: 'Desenvolvedor Back-end Jr',
                company: 'VF PAR',
                location: 'Brasília, DF – Brasil',
                description: 'Desenvolvimento e manutenção dos sistemas internos com NestJS, TypeORM e PostgreSQL no back-end, e React no front-end. Implementação de APIs REST, automações com n8n, integrações via Evolution API e Chatwoot para atendimento via WhatsApp. Deploy via Easypanel, monitoramento com Grafana e fluxo de trabalho orientado a Kanban.',
                current: true,
                tags: ['NestJS', 'PostgreSQL', 'React', 'n8n', 'Docker'],
            },
            {
                role: 'Analista de Q.A',
                company: 'TopSapp',
                location: 'Sinop, MT – Brasil',
                period: 'Dezembro 2025 – Março 2026',
                description: 'Execução de testes funcionais, de regressão e validação de fluxos críticos em sistemas web. Identificação e documentação de bugs, garantindo estabilidade e qualidade das entregas antes e após cada deploy.',
                current: false,
                tags: ['Testes', 'QA', 'Regressão'],
            },
            {
                role: 'Analista de Implantação de Sistemas',
                company: 'Ecocentauro',
                location: 'Sinop, MT – Brasil',
                period: 'Janeiro 2024 – Dezembro 2025',
                description: 'Criação de relatórios detalhados com Crystal Reports e FastReports, utilizando SQL para extração, tratamento e formatação de dados conforme requisitos de cada cliente. Apoio na implantação e configuração de sistemas.',
                current: false,
                tags: ['SQL', 'Crystal Reports', 'FastReports'],
            },
            {
                role: 'Assistente Administrativo',
                company: 'Autoescola Meridional',
                location: 'Sinop, MT – Brasil',
                period: 'Fevereiro 2023 – Janeiro 2024',
                description: 'Gestão de agendamentos de aulas teóricas e práticas, controle de documentação e montagem de processos para emissão de CNH.',
                current: false,
                tags: ['Gestão', 'Documentação'],
            },
        ],
        education_items: [
            {
                institution: 'Estácio',
                period: '2025 – 2029',
                degree: 'Bacharelado em Engenharia de Software (Em andamento)',
                detail: 'Previsão de conclusão: 2029 · 2º Semestre',
            },
        ],
        projects_items: [
            {
                title: 'Conversy',
                status: 'ao vivo',
                type: 'Gestão de SDRs',
                date: '2026',
                description: 'Plataforma completa para gestão de times de SDR, com controle de leads, acompanhamento de metas e visão gerencial em tempo real.',
                tags: ['React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'Express.js', 'PostgreSQL'],
                url: 'https://conversy.up.railway.app/',
                statusColor: '#34d399',
            },
            {
                title: 'Portfólio Pessoal',
                status: 'ao vivo',
                type: 'Projeto pessoal',
                date: '2026',
                description: 'Portfólio com integração à API do GitHub, snake de contribuições animado e sistema de internacionalização PT/EN.',
                tags: ['React', 'TypeScript', 'Tailwind CSS', 'GitHub API'],
                url: '#',
                statusColor: '#34d399',
            },
        ],
        blog_items: [] as { title: string; excerpt: string; date: string }[],
        skillCategories: {
            all: 'todos',
            frontend: 'frontend',
            backend: 'backend',
            database: 'banco de dados',
            tools: 'ferramentas',
        },
        skillLegend: [
            { range: '1–4', label: 'Básico' },
            { range: '5', label: 'Conheço e utilizo' },
            { range: '6–10', label: 'Intermediário / Avançado' },
        ],
    },
    en: {
        openToWork: 'Open to opportunities',
        roles: ['Back-End Developer', 'Software Engineer', 'Full-Stack Developer'],
        location: 'Brasília, DF – Brazil',
        repos: 'Repos',
        followers: 'Followers',
        following: 'Following',
        about: 'about',
        aboutText: 'Full-Stack Developer focused on back-end, specialized in NestJS, TypeORM and PostgreSQL. Hands-on experience building REST APIs, automations with n8n and integrations with external services like OpenAI and Evolution API. I work with Docker, Git versioning and deployment via Easypanel, monitoring environments with Grafana in agile Kanban cycles. Currently pursuing a degree in Software Engineering, constantly seeking technical and professional growth.',
        experience: 'experience',
        projects: 'projects',
        education: 'education',
        skills: 'skills',
        blog: 'blog',
        present: 'current',
        website: 'visit',
        footer: '© {year} · Lucas G. Amorim Steffen',
        promptPrefix: '~/portfolio',
        experience_items: [
            {
                role: 'Junior Back-end Developer',
                company: 'VF PAR',
                location: 'Brasília, DF – Brazil',
                description: 'Development and maintenance of internal systems using NestJS, TypeORM and PostgreSQL on the back-end, and React on the front-end. REST API implementation, automations with n8n, integrations via Evolution API and Chatwoot for WhatsApp support. Deploy via Easypanel, monitoring with Grafana and Kanban-driven workflow.',
                current: true,
                tags: ['NestJS', 'PostgreSQL', 'React', 'n8n', 'Docker'],
            },
            {
                role: 'Q.A. Analyst',
                company: 'TopSapp',
                location: 'Sinop, MT – Brazil',
                period: 'December 2025 – March 2026',
                description: 'Executed functional, regression, and critical workflow testing across web systems. Identified and documented bugs, ensuring product stability and quality before and after each deployment.',
                current: false,
                tags: ['Testing', 'QA', 'Regression'],
            },
            {
                role: 'Systems Implementation Analyst',
                company: 'Ecocentauro',
                location: 'Sinop, MT – Brazil',
                period: 'January 2024 – December 2025',
                description: 'Built detailed reports using Crystal Reports and FastReports, leveraging SQL to extract, process, and format data per client requirements. Supported system deployment and configuration.',
                current: false,
                tags: ['SQL', 'Crystal Reports', 'FastReports'],
            },
            {
                role: 'Administrative Assistant',
                company: 'Autoescola Meridional',
                location: 'Sinop, MT – Brazil',
                period: 'February 2023 – January 2024',
                description: "Managed scheduling of theoretical and practical driving lessons, handled documentation, and assembled CNH (driver's license) application files in compliance with DETRAN requirements.",
                current: false,
                tags: ['Management', 'Documentation'],
            },
        ],
        education_items: [
            {
                institution: 'Estácio',
                period: '2025 – 2029',
                degree: "Bachelor's in Software Engineering (Ongoing)",
                detail: 'Expected graduation: 2029 · 2nd Semester',
            },
        ],
        projects_items: [
            {
                title: 'Conversy',
                status: 'live',
                type: 'SDR management',
                date: '2026',
                description: 'Complete platform for SDR team management, featuring lead tracking, goal monitoring and real-time management dashboards.',
                tags: ['React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'Express.js', 'PostgreSQL'],
                url: 'https://conversy.up.railway.app/',
                statusColor: '#34d399',
            },
            {
                title: 'Personal Portfolio',
                status: 'live',
                type: 'Personal project',
                date: '2026',
                description: 'Portfolio with GitHub API integration, animated contribution snake and PT/EN internationalization system.',
                tags: ['React', 'TypeScript', 'Tailwind CSS', 'GitHub API'],
                url: '#',
                statusColor: '#34d399',
            },
        ],
        blog_items: [] as { title: string; excerpt: string; date: string }[],
        skillCategories: {
            all: 'all',
            frontend: 'frontend',
            backend: 'backend',
            database: 'database',
            tools: 'tools',
        },
        skillLegend: [
            { range: '1–4', label: 'Basic' },
            { range: '5', label: 'Know & use it' },
            { range: '6–10', label: 'Intermediate / Advanced' },
        ],
    },
}
export const GITHUB_USERNAME = 'Lucas-Steffen'

