export const GITHUB_USERNAME = 'Lucas-Steffen'

export const STACK = [
    { name: 'JavaScript', group: 'languages', level: 6, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
    { name: 'TypeScript', group: 'languages', level: 7, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg' },
    { name: 'SQL', group: 'languages', level: 7, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azuresqldatabase/azuresqldatabase-original.svg' },
    { name: 'React', group: 'frontend', level: 5, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
    { name: 'Tailwind CSS', group: 'frontend', level: 5, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg' },
    { name: 'Node.js', group: 'backendData', level: 7, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg' },
    { name: 'NestJS', group: 'backendData', level: 7, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nestjs/nestjs-original.svg' },
    { name: 'Express.js', group: 'backendData', level: 5, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg' },
    { name: 'TypeORM', group: 'backendData', level: 6, icon: 'https://typeorm.io/img/typeorm-icon-colored.png' },
    { name: 'PostgreSQL', group: 'backendData', level: 7, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
    { name: 'MySQL', group: 'backendData', level: 5, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
    { name: 'Firebird', group: 'backendData', level: 7, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/firebird/firebird-original.svg' },
    { name: 'Redis', group: 'backendData', level: 6, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg' },
    { name: 'BullMQ', group: 'backendData', level: 6, icon: '/stack-icons/bullmq.svg' },
    { name: 'REST APIs', group: 'backendData', level: 8, icon: 'https://cdn.simpleicons.org/openapiinitiative/6BA539' },
    { name: 'Swagger', group: 'backendData', level: 7, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swagger/swagger-original.svg' },
    { name: 'JWT', group: 'backendData', level: 7, icon: '/stack-icons/jwt.svg' },
    { name: 'Docker', group: 'devopsObservability', level: 6, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
    { name: 'AWS', group: 'devopsObservability', level: 4, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg' },
    { name: 'Easypanel', group: 'devopsObservability', level: 6, icon: 'https://cdn.simpleicons.org/easypanel/34D399' },
    { name: 'Grafana', group: 'devopsObservability', level: 4, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/grafana/grafana-original.svg' },
    { name: 'Pino', group: 'devopsObservability', level: 5, icon: 'https://cdn.simpleicons.org/pino/687634' },
    { name: 'n8n', group: 'devopsObservability', level: 6, icon: 'https://devicons.railway.com/i/n8n.svg' },
    { name: 'Jest', group: 'testingTooling', level: 5, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jest/jest-plain.svg' },
    { name: 'Git', group: 'testingTooling', level: 8, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
    { name: 'GitHub', group: 'testingTooling', level: 7, icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg' },
] as const

const shared = {
    githubUsername: GITHUB_USERNAME,
    email: 'lucasgabriel.programador@gmail.com',
    linkedin: 'https://linkedin.com/in/lucasteffen',
    github: `https://github.com/${GITHUB_USERNAME}`,
    instagram: 'https://www.instagram.com/lucasg.dev/',
}

export const T = {
    pt: {
        ...shared,
        eyebrow: 'ENGENHEIRO DE SOFTWARE BACKEND · SINOP, MT',
        portraitRole: 'ENGENHEIRO DE SOFTWARE\nBACKEND',
        headline: 'Construo o backend que mantém produtos em movimento.',
        intro: 'Engenheiro de Software Backend especializado em TypeScript, Node.js e NestJS. Projeto APIs, integrações e rotinas assíncronas com atenção a regras de negócio, segurança e operação em produção.',
        primaryCta: 'Conheça meu trabalho',
        location: 'Sinop, MT · Brasil',
        repos: 'repositórios',
        followers: 'seguidores',
        following: 'seguindo',
        proof: [
            { value: '100%', label: 'foco em backend' },
            { value: 'REST', label: 'APIs e integrações' },
            { value: 'SQL', label: 'dados e modelagem' },
            { value: 'PROD', label: 'deploy e observabilidade' },
        ],
        architecturePanel: {
            ariaLabel: 'Visão geral da arquitetura backend', file: 'arquitetura.visao-geral',
            request: 'REQUISIÇÃO', application: 'APLICAÇÃO', async: 'ASSÍNCRONO', data: 'DADOS',
            endpoint: 'POST /v1/recurso', appDetail: 'guards · serviços · DTOs', asyncDetail: 'tarefas · retentativas · eventos', dataDetail: 'TypeORM · migrations',
            info: 'INFO', requestDone: 'requisição concluída', queue: 'FILA', jobSent: 'tarefa enviada', waiting: 'aguardando', auth: 'AUTH', permissionChecked: 'permissão verificada', allowed: 'permitida',
        },
        about: 'como eu trabalho',
        aboutLead: 'Backend não é apenas entregar endpoints.',
        aboutText: 'Meu trabalho conecta regras de negócio, dados e serviços externos em sistemas previsíveis e fáceis de manter. No dia a dia, atuo do desenho do contrato e da modelagem até filas, autenticação, logs, testes, migrations e deploy.',
        principles: [
            { code: '01', title: 'Contratos claros', text: 'DTOs validados, documentação OpenAPI e respostas consistentes para quem consome a API.' },
            { code: '02', title: 'Dados confiáveis', text: 'Modelagem relacional, migrations e transações tratadas como parte central do produto.' },
            { code: '03', title: 'Operação visível', text: 'Logs estruturados, health checks, filas monitoráveis e falhas que deixam pistas úteis.' },
        ],
        experience: 'experiência',
        present: 'atual',
        experience_items: [
            {
                role: 'Engenheiro de Software Backend', company: 'VF PAR', location: 'Sinop, MT · Brasil', current: true,
                description: 'Desenvolvimento e evolução de serviços backend para operações de mobilidade e sistemas internos. Atuação em APIs NestJS, regras de negócio, integrações externas, processamento assíncrono, controle de acesso e persistência de dados.',
                highlights: ['APIs REST modulares com NestJS e TypeORM', 'Integrações com SAP, pagamentos, mensageria e serviços AWS', 'Filas com BullMQ/Redis, autenticação JWT e autorização RBAC', 'Testes, migrations, logs estruturados, Docker e monitoramento'],
                tags: ['TypeScript', 'NestJS', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
            },
            {
                role: 'Analista de Q.A.', company: 'TopSapp', location: 'Sinop, MT · Brasil', period: 'Dez 2025 — Mar 2026', current: false,
                description: 'Validação de fluxos críticos e análise de falhas em sistemas web, experiência que hoje influencia a forma como desenho contratos, cenários de erro e testes de backend.',
                highlights: ['Testes funcionais e de regressão', 'Documentação e reprodução de bugs'], tags: ['Qualidade', 'Regressão', 'Análise de falhas'],
            },
            {
                role: 'Analista de Implantação de Sistemas', company: 'Ecocentauro', location: 'Sinop, MT · Brasil', period: 'Jan 2024 — Dez 2025', current: false,
                description: 'Implantação de sistemas e criação de relatórios orientados ao negócio, com consultas SQL, tratamento de dados e contato direto com requisitos de clientes.',
                highlights: ['Consultas SQL e análise de dados', 'Crystal Reports e FastReports'], tags: ['SQL', 'Dados', 'Implantação'],
            },
        ],
        work: 'trabalho selecionado',
        workIntro: 'Alguns tipos de problema que resolvo no cotidiano, apresentados sem expor código ou informações internas.',
        work_items: [
            { index: '01', kind: 'Plataformas operacionais', title: 'Backends para operações de mobilidade', description: 'Domínios com veículos, telemetria, vistorias, manutenção, contratos, notificações e rotinas financeiras organizados em módulos de negócio.', architecture: ['NestJS', 'PostgreSQL', 'TypeORM', 'BullMQ', 'Redis'], outcome: 'Regras complexas transformadas em serviços rastreáveis e evolutivos.' },
            { index: '02', kind: 'Integrações corporativas', title: 'Sincronização e fluxos com SAP', description: 'Serviços de integração com mapeamento de documentos, filas, processadores, tratamento de erros e persistência de estado para fluxos assíncronos.', architecture: ['SAP', 'Queues', 'Mappers', 'Events', 'Pino'], outcome: 'Integrações desacopladas, com falhas observáveis e reprocessamento controlado.' },
            { index: '03', kind: 'Pagamentos', title: 'API de integração com Asaas', description: 'Cobranças via PIX, boleto, cartão e links de pagamento, com clientes, webhooks autenticados e ambiente de homologação.', architecture: ['NestJS', 'Axios', 'Webhooks', 'OpenAPI', 'Jest'], outcome: 'Contrato documentado e fluxo de homologação reproduzível de ponta a ponta.' },
            { index: '04', kind: 'Fundação de produto', title: 'Autenticação e autorização reutilizáveis', description: 'Base modular para autenticação JWT, papéis, permissões, filas, e-mail e observabilidade aplicada a novos serviços.', architecture: ['JWT', 'RBAC', 'Redis', 'Swagger'], outcome: 'Uma fundação consistente para iniciar novos backends com menos retrabalho.' },
        ],
        publicProjects: 'projetos públicos',
        projects_items: [
            { title: 'Conversy', status: 'participação encerrada', type: 'Produto SaaS', date: 'Fev 2024 — Jun 2026', description: 'Plataforma para gestão de times de SDR, leads e metas. Durante minha participação, desenvolvi APIs, autenticação e persistência para os fluxos do produto.', tags: ['Node.js', 'Express', 'PostgreSQL', 'REST API'], url: 'https://conversy.up.railway.app/' },
        ],
        education: 'formação',
        education_items: [
            { institution: 'Fasipe', period: 'Em andamento', degree: 'Análise e Desenvolvimento de Sistemas', detail: 'Graduação em andamento' },
        ],
        skills: 'stack de trabalho',
        stackIntro: 'Tecnologias que utilizo no desenvolvimento e manutenção de sistemas, organizadas por área. Os níveis representam minha experiência prática atual em uma escala de 0 a 10.',
        stackGroups: { all: 'Todas', languages: 'Linguagens', frontend: 'Frontend', backendData: 'Backend e Dados', devopsObservability: 'DevOps e Observabilidade', testingTooling: 'Testes e Ferramentas' },
        skillLevelLabel: 'de 10',
        socialLabel: 'CONECTE-SE',
        socialTitle: 'Vamos manter contato.',
        socialText: 'Acompanhe meus projetos, conteúdos e experiências sobre engenharia de software e desenvolvimento backend.',
        socialFollow: 'Seguir no',
        footer: '© {year} · Lucas G. Amorim Steffen · Engenheiro de Software Backend',
    },
    en: {
        ...shared,
        eyebrow: 'BACKEND SOFTWARE ENGINEER · SINOP, MT',
        portraitRole: 'BACKEND SOFTWARE\nENGINEER',
        headline: 'I build the backend that keeps products moving.',
        intro: 'Backend Software Engineer specialized in TypeScript, Node.js and NestJS. I design APIs, integrations and asynchronous workflows with close attention to business rules, security and production operations.',
        primaryCta: 'See my work', location: 'Sinop, MT · Brazil', repos: 'repositories', followers: 'followers', following: 'following',
        proof: [{ value: '100%', label: 'backend focus' }, { value: 'REST', label: 'APIs & integrations' }, { value: 'SQL', label: 'data & modeling' }, { value: 'PROD', label: 'delivery & observability' }],
        architecturePanel: {
            ariaLabel: 'Backend architecture overview', file: 'architecture.overview',
            request: 'REQUEST', application: 'APPLICATION', async: 'ASYNC', data: 'DATA',
            endpoint: 'POST /v1/resource', appDetail: 'guards · services · DTOs', asyncDetail: 'jobs · retries · events', dataDetail: 'TypeORM · migrations',
            info: 'INFO', requestDone: 'request completed', queue: 'QUEUE', jobSent: 'job dispatched', waiting: 'waiting', auth: 'AUTH', permissionChecked: 'permission verified', allowed: 'allowed',
        },
        about: 'how I work', aboutLead: 'Backend is more than shipping endpoints.', aboutText: 'My work connects business rules, data and external services into predictable, maintainable systems. I work from contracts and modeling through queues, authentication, logs, tests, migrations and deployment.',
        principles: [{ code: '01', title: 'Clear contracts', text: 'Validated DTOs, OpenAPI documentation and consistent responses for API consumers.' }, { code: '02', title: 'Reliable data', text: 'Relational modeling, migrations and transactions treated as core product concerns.' }, { code: '03', title: 'Visible operations', text: 'Structured logs, health checks, observable queues and failures that leave useful evidence.' }],
        experience: 'experience', present: 'current',
        experience_items: [
            { role: 'Backend Software Engineer', company: 'VF PAR', location: 'Sinop, MT · Brazil', current: true, description: 'Development and evolution of backend services for mobility operations and internal systems. Working with NestJS APIs, business rules, external integrations, asynchronous processing, access control and data persistence.', highlights: ['Modular REST APIs with NestJS and TypeORM', 'SAP, payment, messaging and AWS service integrations', 'BullMQ/Redis queues, JWT authentication and RBAC authorization', 'Tests, migrations, structured logs, Docker and monitoring'], tags: ['TypeScript', 'NestJS', 'PostgreSQL', 'Redis', 'Docker', 'AWS'] },
            { role: 'Q.A. Analyst', company: 'TopSapp', location: 'Sinop, MT · Brazil', period: 'Dec 2025 — Mar 2026', current: false, description: 'Validated critical workflows and analyzed failures in web systems—experience that now shapes how I design contracts, error scenarios and backend tests.', highlights: ['Functional and regression testing', 'Bug documentation and reproduction'], tags: ['Quality', 'Regression', 'Failure analysis'] },
            { role: 'Systems Implementation Analyst', company: 'Ecocentauro', location: 'Sinop, MT · Brazil', period: 'Jan 2024 — Dec 2025', current: false, description: 'System implementation and business reporting using SQL queries, data processing and direct contact with customer requirements.', highlights: ['SQL queries and data analysis', 'Crystal Reports and FastReports'], tags: ['SQL', 'Data', 'Implementation'] },
        ],
        work: 'selected work', workIntro: 'A few kinds of problems I solve in daily work, presented without exposing internal code or information.',
        work_items: [
            { index: '01', kind: 'Operational platforms', title: 'Backends for mobility operations', description: 'Vehicle, telemetry, inspection, maintenance, contract, notification and financial domains organized into business modules.', architecture: ['NestJS', 'PostgreSQL', 'TypeORM', 'BullMQ', 'Redis'], outcome: 'Complex rules turned into traceable, evolvable services.' },
            { index: '02', kind: 'Enterprise integrations', title: 'SAP synchronization workflows', description: 'Integration services with document mapping, queues, processors, error handling and state persistence for asynchronous flows.', architecture: ['SAP', 'Queues', 'Mappers', 'Events', 'Pino'], outcome: 'Decoupled integrations with observable failures and controlled retries.' },
            { index: '03', kind: 'Payments', title: 'Asaas integration API', description: 'PIX, boleto, card and payment-link flows, including customers, authenticated webhooks and sandbox tooling.', architecture: ['NestJS', 'Axios', 'Webhooks', 'OpenAPI', 'Jest'], outcome: 'A documented contract and reproducible end-to-end certification flow.' },
            { index: '04', kind: 'Product foundation', title: 'Reusable authentication and authorization', description: 'Modular foundation for JWT authentication, roles, permissions, queues, email and observability in new services.', architecture: ['JWT', 'RBAC', 'Redis', 'Swagger'], outcome: 'A consistent baseline to start backend services with less repeated work.' },
        ],
        publicProjects: 'public projects', projects_items: [{ title: 'Conversy', status: 'participation ended', type: 'SaaS product', date: 'Feb 2024 — Jun 2026', description: 'Platform for SDR team, lead and target management. During my involvement, I developed APIs, authentication and persistence for the product workflows.', tags: ['Node.js', 'Express', 'PostgreSQL', 'REST API'], url: 'https://conversy.up.railway.app/' }],
        education: 'education', education_items: [
            { institution: 'Fasipe', period: 'In progress', degree: 'Systems Analysis and Development', detail: 'Undergraduate degree in progress' },
        ],
        skills: 'working stack', stackIntro: 'Technologies I use to build and maintain systems, organized by area. Levels represent my current hands-on experience on a 0–10 scale.',
        stackGroups: { all: 'All', languages: 'Languages', frontend: 'Frontend', backendData: 'Backend & Data', devopsObservability: 'DevOps & Observability', testingTooling: 'Testing & Tooling' },
        skillLevelLabel: 'out of 10',
        socialLabel: 'CONNECT',
        socialTitle: 'Let’s stay connected.',
        socialText: 'Follow my projects, content and experiences in software engineering and backend development.',
        socialFollow: 'Follow on',
        footer: '© {year} · Lucas G. Amorim Steffen · Backend Software Engineer',
    },
} as const

export type PortfolioCopy = (typeof T)[keyof typeof T]
