/* eslint-disable @typescript-eslint/no-explicit-any -- translation data is a runtime-selected union */
import { useState } from 'react'
import { ArrowSquareOutIcon,CalendarIcon,TerminalIcon } from '@phosphor-icons/react'
import { SKILLS } from '../data'
import type { SkillCategory } from '../types'
import { Reveal,Section } from './PagePrimitives'
const stack={display:'flex',flexDirection:'column',gap:'12px'} as const
const tags=(items:string[])=><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{items.map(x=><span key={x} className="tag">{x}</span>)}</div>
export function AboutSection({copy}:{copy:any}){return <Section id="about" title={copy.about}><Reveal><div className="card" style={{padding:'24px 28px'}}><div style={{fontFamily:'var(--mono)',fontSize:11,color:'var(--text-dim)',marginBottom:14}}><TerminalIcon size={12}/> cat <span style={{color:'var(--cyan)'}}>README.md</span></div><p style={{color:'var(--text-muted)',lineHeight:1.85,fontSize:14.5}}>{copy.aboutText}</p></div></Reveal></Section>}
export function ExperienceSection({copy}:{copy:any}){return <Section id="experience" title={copy.experience}><div style={stack}>{copy.experience_items.map((x:any,i:number)=><Reveal key={x.role+x.company} delay={i*70}><article className="card" style={{padding:'20px 24px'}}><div style={{display:'flex',justifyContent:'space-between',flexWrap:'wrap',marginBottom:10}}><div><h3 style={{color:'var(--text)',fontSize:14}}>{x.role} {x.current&&<span className="tag">{copy.present}</span>}</h3><span style={{fontFamily:'var(--mono)',color:'var(--cyan)',fontSize:12}}>{x.company} · {x.location}</span></div>{x.period&&<span style={{color:'var(--text-dim)',fontSize:10}}><CalendarIcon size={11}/> {x.period}</span>}</div><p style={{color:'var(--text-muted)',fontSize:13.5,lineHeight:1.75,marginBottom:12}}>{x.description}</p>{tags(x.tags)}</article></Reveal>)}</div></Section>}
export function ProjectsSection({copy}:{copy:any}){return <Section id="projects" title={`${copy.projects} (${copy.projects_items.length})`}><div style={stack}>{copy.projects_items.map((x:any,i:number)=><Reveal key={x.title} delay={i*70}><article className="card" style={{padding:'20px 24px'}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:10}}><div><h3 style={{color:'var(--text)',fontSize:14}}>{x.title}</h3><small style={{color:'var(--text-dim)'}}>{x.type} · {x.date}</small></div><a href={x.url} target="_blank" rel="noreferrer" style={{color:x.statusColor,textDecoration:'none',fontSize:11}}><ArrowSquareOutIcon size={12}/> {copy.website}</a></div><p style={{color:'var(--text-muted)',fontSize:13.5,lineHeight:1.75,marginBottom:14}}>{x.description}</p>{tags(x.tags)}</article></Reveal>)}</div></Section>}
export function EducationSection({copy}:{copy:any}){return <Section id="education" title={copy.education}><div style={stack}>{copy.education_items.map((x:any)=><Reveal key={x.institution}><article className="card" style={{padding:'20px 24px'}}><h3 style={{color:'var(--text)',fontSize:14}}>{x.institution} <small style={{color:'var(--text-dim)'}}>{x.period}</small></h3><p style={{color:'var(--cyan)',fontSize:12}}>{x.degree}</p><small style={{color:'var(--text-dim)'}}>{x.detail}</small></article></Reveal>)}</div></Section>}
export function SkillsSection({copy}:{copy:any}){const [filter,setFilter]=useState<SkillCategory>('all');const cats:SkillCategory[]=['all','frontend','backend','database','tools'];const skills=Object.entries(SKILLS).filter(([c])=>filter==='all'||c===filter).flatMap(([,x])=>x);return <Section id="skills" title={copy.skills}><Reveal><div style={{display:'flex',gap:6,marginBottom:24}}>{cats.map(c=><button key={c} className={`filter-btn${filter===c?' active':''}`} onClick={()=>setFilter(c)}>{copy.skillCategories[c]}</button>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(100px,1fr))',gap:10}}>{skills.map(x=><div key={x.name} className="skill-card"><div style={{height:36}}>{x.icon?<img src={x.icon} alt="" width={36} height={36}/>:x.name[0]}</div><span style={{color:'var(--text-muted)',fontSize:10}}>{x.name}</span><span style={{color:x.level<=4?'#f59e0b':x.level===5?'#38bdf8':'#34d399',fontSize:10}}>{x.level}/10</span></div>)}</div></Reveal></Section>}
export function BlogSection({copy}:{copy:any}){if(!copy.blog_items.length)return null;return <Section id="blog" title={copy.blog}>{copy.blog_items.map((x:any)=><article key={x.title} className="card" style={{padding:20}}>{x.title}</article>)}</Section>}
